baseurl = "/"
languageCode = "en-us"
title = "TPVSports Says Hello!"
theme = "tpvs16"

[permalinks]
  podcast = "/:year/:month/:day/:slug"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "tpvsports.net's Awesome Hugo Site"
  episode = "One"
  author = "Sir Lawrence Davis"
  PublishDate = "2006-01-02"
  soundcloud = ""

[[menu.main]]
  name = "home"
  identifier = "home"
  title = "home"
  weight = 100
  url = "/"

[[menu.main]]
  name = "archive"
  identifier = "archive"
  title = "archive"
  type = "archive"
  weight = 1
  url = "/podcast"
  slug = "/archive"
